### PR TITLE
 Add interface for selecting different graphs #54 

### PR DESCRIPTION
**Pull request by begeeben**

### CODE REVIEW

**Comment by dwi2** [comment]
@shamenchens , please help to review this patch

**Comment by shamenchens** [comment]
@begeeben , looks sane but could we have unit test on it?

**Comment by dwi2** [comment]
+1 for unit tests :grin:

**Comment by begeeben** [comment]
Per discussion, skip view module unit test for now. Add integration test for view later.

**Comment by dwi2** [comment]
looks good to me

**Pull request merged**
