### PR TITLE
fixed#77 - Fully supports ES6 (part1)

### PR DESCRIPTION
**Pull request by snowmantw**
1. Add Acorn parser to support ES6 syntax
2. Forked the parser's walker to modify nodes on-the-fly to do static AOP
3. Add an 'integration' test. Although I think we should design or adopt some test frameworks when it grows up

Set review! @begeeben

### CODE REVIEW

**Comment by dwi2** [comment]
@snowmantw Please ping us when this patch is ready! :+1:

**Comment by begeeben** [comment]
@snowmantw Thanks for the great work! The Espect module does much powerful js parsing and flexible logging than the original debuguy parser. It's our pleasure to have this functionality in this debugging tool and it will enhance logging flexibility in javascript. It'd be great that the Espect lib be required as an independent node module because of its purpose and scale which is even bigger than debuguy itself. Once the Espect repo (which I assume is ready) and npm registry are completed please feel free to modify this PR and we'll happily merge it into debuguy!

**Comment by snowmantw** [comment]
I just updated the patch, and make sure to pull Espect.js is OK. I also changed the title, since I've found the "ES6" functions now are supported to at least what Gaia used (although this target is huge and complicated enough). The more complicated things, like module and classes, since it's not used in the target, there are no tests to guarantee the generator works well, too. I'm sure the parser Acorn supports all things Babel supports, including what I said. However, the generator I used here (escodegen) is always the problem.

**Comment by snowmantw** [comment]
So @dwi2 you can merge this PR. Sorry for delaying so long.

**Comment by dwi2** [comment]
Thanks for your patch

**Pull request merged**
